# Generated by Django 3.2 on 2023-06-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='placeholder.jpeg', null=True, upload_to='images'),
        ),
    ]
